# Modelización y simulación {-}

> Cada vez hay más evidencia de que la "era de la modelización", que dominó las actividades teóricas de las ciencias durante mucho tiempo, está a punto de ser reemplazada o, al menos, complementada de forma duradera por la "era de la simulación".^[Hartmann, S. (2005). The world as a process: Simulations in the natural and social sciences. [http://philsci-archive.pitt.edu/2412/](http://philsci-archive.pitt.edu/2412/)]

La modelización es uno de los temas más importantes que puedes aprender. La modelización se utiliza en microbiología, macroeconomía, estudios urbanos, sociología, psicología, salud pública, informática y, por supuesto, estadística. De hecho, la modelización es un método que se utiliza en casi todas las disciplinas. Muchos piensan que es una habilidad importante que hay que aprender porque está muy extendida. Si bien esto es cierto, es aún más importante la estrecha relación que existe entre las habilidades de modelización y las habilidades más generales de resolución de problemas. Starfield, Smith y Bleloch (1994) resumieron muy bien este sentimiento cuando escribieron: "aprender a modelizar está ligado a aprender a resolver problemas y a pensar con imaginación y determinación" (p. x).^[Starfield, A. M., Smith, K. A., & Bleloch, A. L. (1994). How to model it: Problem solving for the computer age. Edina, MN: Burgess International Group, Inc.]

Un modelo es una representación simplificada de un sistema que puede utilizarse para promover la comprensión de un sistema más complejo. Por ejemplo, los meteorólogos utilizan los ordenadores para construir modelos del clima para entender y predecir el tiempo atmosférico. El modelo computacional incluye comportamientos o propiedades que se corresponden, de alguna manera, con el sistema particular del mundo real del clima. Sin embargo, los modelos computacionales no incluyen todos los detalles posibles del clima. Todos los modelos omiten detalles y emplean algunas especificaciones (muchas) erróneas. Esto se debe a que todos los modelos son simplificaciones de la realidad. Dado que todos los modelos son simplificaciones de la realidad, siempre hay que elegir el nivel de detalle que se incluye en el modelo. Si se incluye poco detalle en el modelo, se corre el riesgo de omitir interacciones relevantes y el modelo resultante no favorece la comprensión. Si se incluyen demasiados detalles en el modelo, éste puede resultar excesivamente complicado e impedir el desarrollo de la comprensión.

Los modelos tienen muchos propósitos, pero se utilizan principalmente para comprender mejor los fenómenos del mundo real. Los usos comunes de los modelos son para la descripción, exploración, predicción y clasificación. Por ejemplo, Google crea modelos para comprender y predecir las tendencias de búsqueda en internet de las personas. Estos modelos luego se utilizan para ayudar a Google a realizar mejores y más eficientes búsquedas de información. Otro ejemplo es Netflix. Netflix crea modelos para comprender las características de las películas que sus clientes han calificado con altas puntuaciones para que luego puedan recomendar otras películas que la persona pueda disfrutar. Amazon y Apple iTunes usan modelos de manera similar.

### Esquema y Objetivos de la Unidad 1 {-}

En esta unidad comenzarás explorando las ideas de la aleatoriedad. La aleatoriedad impregna y es, de hecho, fundamental para la estadística. Luego, aprenderás a usar TinkerPlots™ para modelizar varios procesos aleatorios y generar resultados a partir de esos modelos. Al generar datos a partir de diferentes modelos, ganarás experiencia en la consideración de la variación en los resultados que es producida por estos procesos aleatorios. Esta consideración te ayudará a entender y superar muchas intuiciones humanas erróneas sobre la aleatoriedad.

También se te presentará el proceso de simulación de Monte Carlo y aprenderás a realizar una simulación de Monte Carlo utilizando TinkerPlots™. Este proceso permite generar rápidamente múltiples conjuntos de datos a partir de un modelo para llevar a cabo experimentos hipotéticos. Por ejemplo, podemos hacer la pregunta: ¿Qué probabilidad hay de que llueva tres de los cinco días de mis vacaciones dado un pronóstico específico? Si modelizamos el pronóstico y generamos repetidamente datos para los cinco días de vacaciones, podremos responder a esta pregunta.

A medida que avanzas en la unidad, recuerda que el proceso de modelización es un proceso creativo que a menudo puede ser muy desafiante. A veces, esto puede llevar a la frustración mientras se aprende y se practica parte del material. Pero como nos recuerdan Mosteller et al. (1973), también es una experiencia provechosa, ya que "la modelización no es sólo una técnica de estadística... es un método de estudio que puede aplicarse también en muchos otros campos" (p. xii).^[Mosteller, F., Kruskal, W. H., Link, R. F., Pieters, R. S., & Rising, G. R. (1973). Statistics by example: Finding models. Reading, MA: Addison–Wesley.]

### Aleatoriedad {-}

Un componente crítico de la simulación es el proceso aleatorio utilizado para generar datos. Para que empieces a entender la aleatoriedad, mira el vídeo de YouTube [Secuencias aleatorias: humanos contra monedas](https://www.youtube.com/watch?v=H2lJLXS3AYM).

<br />

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/H2lJLXS3AYM" frameborder="q" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>
