# Generación de Datos a partir de Modelos {-}

Una de las habilidades principales de una persona profesional en estadística aplicada es poder generar datos aleatorios a partir de un modelo. La mayoría de los modelos que encontrarás en este curso se denominan *modelos de probabilidad* o *modelos probabilísticos*. Lo anterior es sólo una forma elegante de asociar probabilidades con diferentes eventos o resultados en un modelo.

Por ejemplo, el modelo de lanzar una moneda "justa" es un modelo de probabilidad. Hay dos eventos/resultados en el modelo: cara y cruz. Cada uno de estos resultados tiene asociada una probabilidad de 0,5. (Tenga en cuenta que aunque podríamos decir 50%, las probabilidades están en la escala de 0 a 1, por lo que se definen usando valores decimales).

En la actividad de clase: *Generación de datos aleatorios*, crearás varios modelos probabilísticos para generar datos sobre gatos. Para prepararse para esta actividad, vea el vídeo tutorial [Simulación de Probabilidad](http://www.tinkerplots.com/movies/probability-simulation) TinkerPlots&trade;.


<br />

<center>
<iframe width="560" height="420" src="https://www.youtube.com/embed/udeuvbJKGeI" frameborder="0" allowfullscreen></iframe>
</center>
